"""empty message

Revision ID: 28a666baf55c
Revises: d197a48c95b6
Create Date: 2020-11-20 12:05:30.570060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28a666baf55c'
down_revision = 'd197a48c95b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stripe_checkout_session', schema=None) as batch_op:
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stripe_checkout_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
