"""empty message

Revision ID: 2d4f5b21b841
Revises: c5820422d762
Create Date: 2020-11-23 16:39:29.211705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d4f5b21b841'
down_revision = 'c5820422d762'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('giftee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_length', sa.Integer(), nullable=True))
        batch_op.drop_column('is_half_year_subscription')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('giftee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_half_year_subscription', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('subscription_length')

    # ### end Alembic commands ###
