"""empty message

Revision ID: 4d7cd3ea3aa2
Revises: e6debb79271e
Create Date: 2020-12-15 14:57:56.253353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d7cd3ea3aa2'
down_revision = 'e6debb79271e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('giftee', schema=None) as batch_op:
        batch_op.drop_column('send_gift_date')
        batch_op.drop_column('test')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('giftee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('send_gift_date', sa.DATE(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
