"""empty message

Revision ID: 710cba01115a
Revises: 28a666baf55c
Create Date: 2020-11-20 12:06:18.707716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '710cba01115a'
down_revision = '28a666baf55c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stripe_checkout_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stripe_checkout_session', schema=None) as batch_op:
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###
