"""empty message

Revision ID: b758ee85fe3f
Revises: 04cffc2357dd
Create Date: 2020-11-18 21:47:28.371364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b758ee85fe3f'
down_revision = '04cffc2357dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('giftee', sa.Column('gifter_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'giftee', 'gifter', ['gifter_id'], ['id'])
    op.drop_index('ix_gifter_email', table_name='gifter')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_gifter_email', 'gifter', ['email'], unique=1)
    op.drop_constraint(None, 'giftee', type_='foreignkey')
    op.drop_column('giftee', 'gifter_id')
    # ### end Alembic commands ###
