"""empty message

Revision ID: c5820422d762
Revises: e093728d4c6a
Create Date: 2020-11-23 16:35:06.920535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5820422d762'
down_revision = 'e093728d4c6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('giftee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_half_year_subscription', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('giftee', schema=None) as batch_op:
        batch_op.drop_column('is_half_year_subscription')

    # ### end Alembic commands ###
