"""empty message

Revision ID: da21758e22b0
Revises: b758ee85fe3f
Create Date: 2020-11-18 22:02:10.927223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da21758e22b0'
down_revision = 'b758ee85fe3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gifter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('giftee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('personal_note', sa.Text(), nullable=True),
    sa.Column('send_gift_date', sa.Date(), nullable=True),
    sa.Column('gifter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gifter_id'], ['gifter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('giftee')
    op.drop_table('gifter')
    # ### end Alembic commands ###
